import { useNavigate } from "react-router-dom";
import { useLang } from "./useLang";

const V1 = "#8B5CF6";
const V2 = "#7C3AED";

const TERMS = {
  en: {
    title: "Terms of Service",
    updated: "Last updated: April 1, 2026",
    intro: "Please read these Terms of Service carefully before using the SellScribe platform. By accessing or using our service, you agree to be bound by these terms.",
    sections: [
      { heading: "1. Acceptance of Terms", body: "By creating an account and using SellScribe (\"Service\"), you agree to be bound by these Terms of Service (\"Terms\"). If you do not agree to these Terms, you may not access or use the Service. These Terms constitute a legally binding agreement between you and SellScribe." },
      { heading: "2. Description of Service", body: "SellScribe is an artificial intelligence-powered platform that generates product listing descriptions for e-commerce marketplaces including Amazon, Shopify, Etsy, eBay, Wildberries, and Kaspi. The Service is provided on a subscription basis with a free tier offering limited monthly generations and paid tiers offering expanded access." },
      { heading: "3. User Accounts and Registration", body: "To access the Service, you must create an account by providing a valid email address and password. You represent that all information you provide is accurate and complete. You are solely responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You may not share your account credentials or transfer your account to any other person." },
      { heading: "4. Acceptable Use Policy", body: "You agree to use the Service solely for lawful purposes and in accordance with these Terms. You may not use the Service to generate content that is false, misleading, fraudulent, defamatory, or in violation of any applicable laws or regulations. You are solely responsible for reviewing, editing, and verifying all content generated through your account before publishing it on any marketplace platform." },
      { heading: "5. Generated Content and Intellectual Property", body: "Content generated by the Service using artificial intelligence is provided to you upon generation. You retain ownership of all generated content. SellScribe retains all rights, title, and interest in and to the Service, including all software, algorithms, and underlying technology. You grant SellScribe a limited, non-exclusive license to process the product information you submit solely for the purpose of generating listing content." },
      { heading: "6. Subscription, Billing, and Cancellation", body: "Paid subscription plans are billed on a monthly basis through our payment processor, Lemon Squeezy. All fees are non-refundable except as required by applicable law or as determined at our sole discretion. You may cancel your subscription at any time through your account settings or by contacting support. Cancellation takes effect at the end of the current billing period. Free tier users are subject to a limit of ten (10) generations per calendar month." },
      { heading: "7. Disclaimer of Warranties", body: "THE SERVICE IS PROVIDED \"AS IS\" AND \"AS AVAILABLE\" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. SELLSCRIBE DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. SELLSCRIBE DOES NOT GUARANTEE THAT GENERATED CONTENT WILL ACHIEVE SPECIFIC SEARCH RANKINGS, CONVERSION RATES, OR SALES RESULTS ON ANY MARKETPLACE PLATFORM." },
      { heading: "8. Limitation of Liability", body: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SELLSCRIBE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES. IN NO EVENT SHALL SELLSCRIBE'S TOTAL LIABILITY EXCEED THE AMOUNTS PAID BY YOU FOR THE SERVICE IN THE THREE (3) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM." },
      { heading: "9. Privacy and Data Processing", body: "Your use of the Service is also governed by our Privacy Policy. We collect your email address and usage data to provide and improve the Service. Product information you enter is transmitted to and processed by the Anthropic API to generate listing content. We do not sell your personal data to third parties." },
      { heading: "10. Termination", body: "SellScribe reserves the right, in its sole discretion, to suspend or terminate your account and access to the Service at any time for violation of these Terms or for any other reason, with or without notice. You may request deletion of your account at any time by contacting support. Upon termination, your right to use the Service ceases immediately." },
      { heading: "11. Modifications to Terms", body: "SellScribe reserves the right to modify these Terms at any time. We will notify users of material changes by posting the updated Terms on our website. Your continued use of the Service following the posting of revised Terms constitutes your acceptance of the changes." },
      { heading: "12. Governing Law", body: "These Terms shall be governed by and construed in accordance with applicable law. Any disputes arising under these Terms shall be resolved through good-faith negotiation before any formal legal proceedings." },
      { heading: "13. Contact Information", body: "If you have questions or concerns regarding these Terms, please contact us through the feedback form available on the SellScribe website." },
    ],
  },
  ru: {
    title: "Условия использования",
    updated: "Последнее обновление: 1 апреля 2026 г.",
    intro: "Пожалуйста, внимательно ознакомьтесь с настоящими Условиями использования перед использованием платформы SellScribe. Получая доступ к Сервису или используя его, вы соглашаетесь соблюдать настоящие Условия.",
    sections: [
      { heading: "1. Принятие Условий", body: "Создавая аккаунт и используя SellScribe («Сервис»), вы соглашаетесь соблюдать настоящие Условия использования («Условия»). Если вы не принимаете настоящие Условия, вы не вправе получать доступ к Сервису или использовать его. Настоящие Условия представляют собой юридически обязывающее соглашение между вами и SellScribe." },
      { heading: "2. Описание Сервиса", body: "SellScribe — это платформа на основе искусственного интеллекта, которая генерирует описания товаров для маркетплейсов, включая Amazon, Shopify, Etsy, eBay, Wildberries и Kaspi. Сервис предоставляется на основе подписки: бесплатный тариф предусматривает ограниченное число ежемесячных генераций, платные тарифы — расширенный доступ." },
      { heading: "3. Аккаунт пользователя и регистрация", body: "Для доступа к Сервису вам необходимо создать аккаунт, указав действительный адрес электронной почты и пароль. Вы гарантируете, что вся предоставляемая информация является точной и достоверной. Вы несёте единоличную ответственность за сохранность учётных данных и за все действия, совершённые под вашим аккаунтом. Передача учётных данных или аккаунта третьим лицам не допускается." },
      { heading: "4. Допустимое использование", body: "Вы соглашаетесь использовать Сервис исключительно в законных целях и в соответствии с настоящими Условиями. Запрещается использовать Сервис для генерации ложного, вводящего в заблуждение, мошеннического, клеветнического или противоправного контента. Вы несёте единоличную ответственность за проверку, редактирование и верификацию всего сгенерированного контента перед его публикацией на любой платформе маркетплейса." },
      { heading: "5. Сгенерированный контент и интеллектуальная собственность", body: "Контент, сгенерированный Сервисом с использованием искусственного интеллекта, передаётся вам в момент создания. Вы сохраняете право собственности на весь сгенерированный контент. SellScribe сохраняет все права на Сервис, включая программное обеспечение, алгоритмы и базовые технологии. Вы предоставляете SellScribe ограниченную неисключительную лицензию на обработку вводимой вами информации о товарах исключительно в целях генерации описаний." },
      { heading: "6. Подписка, оплата и отмена", body: "Платные тарифы оплачиваются ежемесячно через наш платёжный процессор Lemon Squeezy. Все оплаченные суммы не подлежат возврату, за исключением случаев, предусмотренных применимым законодательством или определённых по нашему усмотрению. Вы можете отменить подписку в любое время. Отмена вступает в силу по окончании текущего расчётного периода. Для пользователей бесплатного тарифа установлен лимит в десять (10) генераций в календарный месяц." },
      { heading: "7. Отказ от гарантий", body: "СЕРВИС ПРЕДОСТАВЛЯЕТСЯ «КАК ЕСТЬ» И «ПО МЕРЕ ДОСТУПНОСТИ» БЕЗ КАКИХ-ЛИБО ГАРАНТИЙ. SELLSCRIBE НЕ ГАРАНТИРУЕТ БЕСПЕРЕБОЙНУЮ ИЛИ БЕЗОШИБОЧНУЮ РАБОТУ СЕРВИСА. SELLSCRIBE НЕ ГАРАНТИРУЕТ, ЧТО СГЕНЕРИРОВАННЫЙ КОНТЕНТ ОБЕСПЕЧИТ ОПРЕДЕЛЁННЫЕ ПОЗИЦИИ В ПОИСКОВОЙ ВЫДАЧЕ, УРОВЕНЬ КОНВЕРСИИ ИЛИ ОБЪЁМ ПРОДАЖ НА КАКОМ-ЛИБО МАРКЕТПЛЕЙСЕ." },
      { heading: "8. Ограничение ответственности", body: "В МАКСИМАЛЬНО ДОПУСТИМОЙ ЗАКОНОМ МЕРЕ SELLSCRIBE НЕ НЕСЁТ ОТВЕТСТВЕННОСТИ ЗА КОСВЕННЫЕ, СЛУЧАЙНЫЕ, СПЕЦИАЛЬНЫЕ ИЛИ ШТРАФНЫЕ УБЫТКИ. СОВОКУПНАЯ ОТВЕТСТВЕННОСТЬ SELLSCRIBE НИ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ НЕ ПРЕВЫШАЕТ СУММ, УПЛАЧЕННЫХ ВАМИ ЗА СЕРВИС В ТЕЧЕНИЕ ТРЁХ (3) МЕСЯЦЕВ, ПРЕДШЕСТВОВАВШИХ СОБЫТИЮ, ПОВЛЁКШЕМУ ПРЕДЪЯВЛЕНИЕ ТРЕБОВАНИЯ." },
      { heading: "9. Конфиденциальность и обработка данных", body: "Использование Сервиса также регулируется нашей Политикой конфиденциальности. Мы собираем ваш адрес электронной почты и данные об использовании для предоставления и улучшения Сервиса. Информация о товарах, которую вы вводите, передаётся в API Anthropic и обрабатывается им для генерации описаний. Мы не продаём ваши персональные данные третьим лицам." },
      { heading: "10. Прекращение доступа", body: "SellScribe оставляет за собой право по собственному усмотрению приостановить или прекратить действие вашего аккаунта и доступа к Сервису в любое время в случае нарушения настоящих Условий или по иным причинам — с уведомлением или без него. Вы можете запросить удаление аккаунта в любое время, обратившись в поддержку. После прекращения доступа ваше право на использование Сервиса немедленно прекращается." },
      { heading: "11. Изменение Условий", body: "SellScribe оставляет за собой право в любое время изменять настоящие Условия. О существенных изменениях мы будем уведомлять пользователей путём публикации обновлённых Условий на сайте. Продолжение использования Сервиса после публикации изменений означает ваше согласие с ними." },
      { heading: "12. Применимое право", body: "Настоящие Условия регулируются и толкуются в соответствии с применимым законодательством. Любые споры, возникающие в рамках настоящих Условий, разрешаются путём переговоров в добросовестном порядке до начала каких-либо формальных юридических процедур." },
      { heading: "13. Контактная информация", body: "Если у вас возникли вопросы или замечания в отношении настоящих Условий, пожалуйста, свяжитесь с нами через форму обратной связи, доступную на сайте SellScribe." },
    ],
  },
};

export default function Terms() {
  const navigate = useNavigate();
  const [lang] = useLang();
  const T = TERMS[lang];

  return (
    <div style={{ minHeight: "100vh", background: "#FAFAFA", fontFamily: "var(--font-body)" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,700;12..96,800&family=DM+Sans:wght@300;400;500&display=swap');
        :root { --font-display:'Bricolage Grotesque',sans-serif; --font-body:'DM Sans',sans-serif; }
        * { margin:0; padding:0; box-sizing:border-box; }
      `}</style>

      {/* Nav */}
      <nav style={{ padding: "0 32px", borderBottom: "1px solid #E8E4F0", background: "#fff" }}>
        <div style={{ maxWidth: 720, margin: "0 auto", height: 56, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div onClick={() => navigate("/")} style={{ cursor: "pointer", display: "flex", alignItems: "center", gap: 8 }}>
            <svg viewBox="0 0 80 80" width="22" height="22">
              <defs><linearGradient id="lGt" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stopColor="#A78BFA"/><stop offset="100%" stopColor="#7C3AED"/></linearGradient></defs>
              <rect width="80" height="80" rx="18" fill="rgba(139,92,246,0.08)"/>
              <path d="M24 16 C20 16,18 20,18 24 L18 56 C18 60,20 64,24 64 L48 64 C52 64,54 60,54 56 L54 28" stroke="url(#lGt)" strokeWidth="3" fill="none" strokeLinecap="round"/>
              <path d="M54 28 C54 22,51 18,46 18 L24 18" stroke="url(#lGt)" strokeWidth="3" fill="none" strokeLinecap="round"/>
            </svg>
            <span style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 15, letterSpacing: "-0.02em" }}>
              <span style={{ color: "#1A1330" }}>Sell</span><span style={{ color: V1 }}>Scribe</span>
            </span>
          </div>
          <button onClick={() => navigate(-1)} style={{ padding: "6px 14px", borderRadius: 6, border: "1px solid #D8D4E8", background: "transparent", color: "#6B647A", fontSize: 13, cursor: "pointer", fontFamily: "var(--font-body)" }}>
            ← {lang === "ru" ? "Назад" : "Back"}
          </button>
        </div>
      </nav>

      {/* Document */}
      <div style={{ maxWidth: 720, margin: "0 auto", padding: "48px 32px 80px" }}>

        {/* Header */}
        <div style={{ borderBottom: "2px solid #1A1330", paddingBottom: 20, marginBottom: 28 }}>
          <h1 style={{ fontFamily: "var(--font-display)", fontSize: 24, fontWeight: 800, color: "#1A1330", letterSpacing: "-0.02em", marginBottom: 6 }}>
            {T.title}
          </h1>
          <p style={{ color: "#9B96B8", fontSize: 12, fontWeight: 500, letterSpacing: "0.02em" }}>{T.updated}</p>
        </div>

        {/* Intro */}
        <p style={{ fontSize: 13, color: "#4A4260", lineHeight: 1.75, marginBottom: 32, fontStyle: "italic" }}>
          {T.intro}
        </p>

        {/* Sections */}
        {T.sections.map((s, i) => (
          <div key={i} style={{ marginBottom: 24, paddingBottom: 24, borderBottom: i < T.sections.length - 1 ? "1px solid #EDE9F8" : "none" }}>
            <h2 style={{ fontSize: 13, fontWeight: 700, color: "#1A1330", marginBottom: 8, letterSpacing: "0.01em", textTransform: "uppercase" }}>
              {s.heading}
            </h2>
            <p style={{ fontSize: 13, color: "#3A3350", lineHeight: 1.8, fontWeight: 400 }}>{s.body}</p>
          </div>
        ))}

        <div style={{ marginTop: 48, paddingTop: 24, borderTop: "1px solid #EDE9F8", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <span style={{ fontSize: 12, color: "#9B96B8" }}>SellScribe · sellscribe.app</span>
          <span style={{ fontSize: 12, color: "#9B96B8" }}>{T.updated}</span>
        </div>
      </div>
    </div>
  );
}
